### ISSUE TITLE
Is it currently only to detect a single file? How to detect deadlocks in the entire project?

### ISSUE THREAD

**Issue by Mingwang-Li** [hlisdero/cargo-check-deadlock#22]

**Comment by hlisdero** [comment]
Hi @Mingwang-Li 
Sorry for the late response. Currently it only works with a single file. The file is passed as the input to `rustc`. We would need re-use `cargo` somehow to gather all the files that need to be passed to `rustc`. I have not implemented this yet. It would definitely be a useful feature.
